### ISSUE TITLE
Home link doesn't work, but search link does...

### ISSUE THREAD

**Issue by Jeydin21** [debsishu/Miyou-API#2]
https://streamable.com/pvt4gs

The link from the homepage is https://www.miyou.me/search/SPY%C3%97FAMILY%20Part%202

The link from the search is https://www.miyou.me/category/spy-x-family-part-2

**Comment by debsishu** [comment]
> https://streamable.com/pvt4gs
> 
> The link from the homepage is https://www.miyou.me/search/SPY%C3%97FAMILY%20Part%202
> 
> The link from the search is https://www.miyou.me/category/spy-x-family-part-2

I actually noticed it the other day. But the issue is with the Anilist naming. The anilist naming has an 'x' with the anime name in between which is correct but gogoanime stores the anime without the 'x' so that's why the search doesn't work.

**Comment by debsishu** [comment]
> 

You can try. I've never tried scrapping from Zoro.
