### ISSUE TITLE
error

### ISSUE THREAD

**Issue by well300** [debsishu/Miyou-API#3]
![dffd](https://user-images.githubusercontent.com/90952986/199998034-a609861a-cec1-434e-a1b7-4736c8218c34.PNG)

bro how may i solve this error

**Comment by debsishu** [comment]
> ![dffd](https://user-images.githubusercontent.com/90952986/199998034-a609861a-cec1-434e-a1b7-4736c8218c34.PNG)
> 
> bro how may i solve this error

Can you tell me how to reproduce this error?

**Comment by well300** [comment]
can you give me your whatsapp no.

**Comment by debsishu** [comment]
Check if you have written the .env file correctly

**Comment by well300** [comment]
> Check if you have written the .env file correctly
![well1](https://user-images.githubusercontent.com/90952986/200132209-d09f5a6e-927a-49e7-9bc7-c8d3958068ac.PNG)
![well](https://user-images.githubusercontent.com/90952986/200132210-e2991b5f-54e5-4837-ba8c-799c423998ae.PNG)

Here i did like this but it showing me this type of error also, can you help me out!

**Comment by debsishu** [comment]
In the .env file, you have to put the domain name where your front end is hosted, not the backend one.

**Comment by well300** [comment]
> In the .env file, you have to put the domain name where your front end is hosted, not the backend one.

i did but giving same error can you run your files ones.

**Comment by debsishu** [comment]
You cannot test the server in browser. It will give you CORS error. For testing you have to use Postman, and add `http://localhost:3000` in the header as Origin

![image](https://user-images.githubusercontent.com/61660793/200178484-01584007-7bf0-448f-a2bd-22b7d4e34b38.png)

**Comment by well300** [comment]
> You cannot test the server in browser. It will give you CORS error. For testing you have to use Postman, and add `http://localhost:3000` in the header as Origin
> 
> ![image](https://user-images.githubusercontent.com/61660793/200178484-01584007-7bf0-448f-a2bd-22b7d4e34b38.png)

thank you brother, it is finally working.
